version: 2.1

orbs:
  go: circleci/go@1.7.3
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_lint_test:
    machine:
      image: ubuntu-2204:2022.10.1
    resource_class: large
    steps:
      - go/install:
          version: "1.19"
      - checkout
      - run:
          name: Print Go environment
          command: "go env"
      - go/load-cache:
          key: go-mod-v6-{{ checksum "go.sum" }}
      - go/mod-download
      - run:
          name: Install Dependencies
          command: sudo apt-get install libzmq3-dev
      - go/save-cache:
          key: go-mod-v6-{{ checksum "go.sum" }}
          path: "/home/circleci/.go_workspace/pkg/mod"
      - run:
          name: Build vigilante
          command: make build
      - run:
          name: Lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.52.2
            ./bin/golangci-lint run
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Run integration tests
          command: |
            make test-e2e

  build_docker:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - checkout
      - aws-ecr/build-image:
          push-image: false
          dockerfile: Dockerfile
          path: ./contrib/images/vigilante
          build-path: ./
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG"
          repo: "$CIRCLE_PROJECT_REPONAME"
      - run:
          name: Save Docker image to export it to workspace
          command: |
            docker save $(docker image ls --format '{{.Repository}}:{{.Tag}}') > /tmp/vigilante.tar
      - persist_to_workspace:
          root: /tmp
          paths:
            - vigilante.tar

  push_docker:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image from workspace
          command: |
            docker load -i /tmp/vigilante.tar
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "$AWS_REGION"
      - aws-ecr/push-image:
          registry-id: AWS_ECR_REGISTRY_ID
          region: "$AWS_REGION"
          repo: "$CIRCLE_PROJECT_REPONAME"
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG"

workflows:
  CI:
    jobs:
      - build_lint_test
      - build_docker:
          filters:
            tags:
              only: /.*/
      - push_docker:
          requires:
            - build_docker
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - main
                - dev
